{{- if .Values.agent.enabled }}
{{- if not .Values.agent.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myrmex-hive.agent.fullname" . }}
  labels:
    {{- include "myrmex-hive.agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  agent_config.json: |
    {{- $cfg := deepCopy .Values.agent.config }}
    {{- $_ := set $cfg "private_key_path" "/app/secrets/id_ed25519" }}
    {{- if not $cfg.gateway_addr }}
    {{- $_ := set $cfg "gateway_addr" (include "myrmex-hive.gateway.addr" $) }}
    {{- end }}
    {{- toJson $cfg | nindent 4 }}
  id_ed25519: |
    {{- .Values.agent.privateKey | nindent 4 }}
{{- end }}
{{- end }}
