{{- if .Values.gateway.enabled }}
{{- if not .Values.gateway.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myrmex-hive.gateway.fullname" . }}
  labels:
    {{- include "myrmex-hive.gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  gateway_config.json: |
    {{- $cfg := merge (deepCopy .Values.gateway.config.extra) (omit .Values.gateway.config "extra") }}
    {{- if .Values.gateway.tls.enabled }}
    {{- $cfg = merge $cfg (dict "tls_cert_path" .Values.gateway.tls.certPath "tls_key_path" .Values.gateway.tls.keyPath) }}
    {{- end }}
    {{- toJson $cfg | nindent 4 }}
  authorized_keys: |
    {{- .Values.gateway.authorizedKeys | nindent 4 }}
{{- end }}
{{- end }}
