name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Verify Go Format and Lint
        run: |
          go fmt ./...
          go vet ./...

      - name: Run Unit Tests
        run: |
          go test -v ./...

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Check Nix Flake
        run: nix flake check

      - name: Build via Nix
        run: nix build
